### ISSUE TITLE
#3 Craft Interview Questions

### ISSUE THREAD

**Issue by sn0wyw01f** [jacksonhooi/INF2001_P5-4#1]
Task Description:
Requirements elicitation is an essential part of the software engineering process, it can be done through interviews and surveys with the target audience/client. It is required to establish the scope of the project, better understand the subject domain and business operations of stakeholders, as well as the needs of stakeholders to formulate use cases for the project.

Goals:
- [x]  Draft questions to ask for the face to face meeting with client

Completion Criteria:
Successful creation of list of questions to ask the client

Allocated Time
2 Weeks

Start Date: 29 Aug 2023
End Date: 15 Sep 2023

**Comment by lokjunneo** [comment]
When is lunch break?

**Comment by lokjunneo** [comment]
How do we assign admins to the system? Do we assume that all managers/ assistant managers have admin rights to the system?

**Comment by Reinakwok** [comment]
Do we have to inform/notify the employee/manager if staff misses deadline request?

**Comment by Reinakwok** [comment]
Does it  open from 9am to 9pm during weekends as well?

**Comment by Reinakwok** [comment]
Does the employees have to indicate when they go for lunch? to show that there are not in the pharmacy for that particular hour

**Comment by jacksonhooi** [comment]
How interactive for the administrative staff to visualize manpower availabilities? Calendar chart etc.?

**Comment by sn0wyw01f** [comment]
Is everyone lunch break at same time? will the store be open during lunch break?

**Comment by sn0wyw01f** [comment]
Can managers and pharmacists be reassigned to other branches?

**Comment by sn0wyw01f** [comment]
Work Done:
Questions have been created for the interview.

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
All goals completed
Issue can be marked as closed

Start Date: 15 Sep 2023
End Date: 15 Sep 2023
