### ISSUE TITLE
#7 Clarify Client's User Requirements through Email

### ISSUE THREAD

**Issue by sweeboon** [jacksonhooi/INF2001_P5-4#10]
Task Description:
Since the f2f meeting wasn't very organized, we shall email the remaining questions to the client instead.
Link for the email draft:
https://docs.google.com/document/d/1Q4HHAsjMZJEo6I-RpGA_3bIwSL-8QnSOW5bqXF5FU6o/edit?usp=sharing

Goals:

- [x] Organize the list of questions to send client
- [x] Email said list of questions to the client
- [x] Get response from the client

Completion Criteria:
Successful clarification of questions in email sent to client

Allocated Time:
1 Week

Start Date: 7/9/2023
End Date: 14/9/2023

**Comment by sn0wyw01f** [comment]
Work Done:
As of 1412hrs 11 Sep 2023, @jacksonhooi has emailed the questions to the client

Effect on Completion Deadline:
Client reply required to lock in the requirements for project

Changes to Completion Criteria:
Two goals completed
 - Organize the list of questions to send client
 - Email said list of questions to the client

Start Date: 8 Sep 2023
End Date: 11 Sep 2023

**Comment by jacksonhooi** [comment]
Work Done:
Client had response to the email.

Effect on Completion Deadline:
Task has been completed on time.


Issue can be marked as closed

Start Date: 8 Sep 2023
End Date: 13 Sep 2023

**Comment by Reinakwok** [comment]
Work Done:
Client had response to the email.

Effect on Completion Deadline:
Task has been completed on time.

Issue can be marked as closed

Start Date: 8 Sep 2023
End Date: 13 Sep 2023
