### ISSUE TITLE
#12 Front End Design - Wireframe Draft

### ISSUE THREAD

**Issue by sweeboon** [jacksonhooi/INF2001_P5-4#11]
Task Description:
Create wireframes to help visualize the process flow and layout of the web application

Goals:

- [x] Draft wireframes for web application created
- [x] Finalize front end design for web application

Completion Criteria:
Successful completion of wireframes for web application, finalized design

Allocated Time:

Start Date:
End Date:

**Comment by sweeboon** [comment]
Wireframe not critical to M1, provisional closing of issue in case M2 requires it

**Comment by Reinakwok** [comment]
Wireframe not critical to M1, provisional closing of issue in case M2 requires it
