### ISSUE TITLE
#10 Create Use Case Diagram

### ISSUE THREAD

**Issue by sweeboon** [jacksonhooi/INF2001_P5-4#13]
Task Description:
Create use case diagram to visualize different aspects of the gathered functional user requirements

Use Case Diagram: Define actions actors can interact with the system
Use Case Description: Apply functional user requirements gathered to the use case description template

Goals:

- [ ] Use Case Diagram

Completion Criteria:
Clear Identification of Actors, full encapsulation of use cases, well-defined Rrlationships

Allocated Time: 7 Days

Start Date: 13 Sept
End Date: 19 Sept

**Comment by sn0wyw01f** [comment]
Work Done:
![Image](https://github.com/jacksonhooi/INF2001_P5-4/assets/121973429/c2e3c936-ed95-4c7d-8f0c-3cea500a9970)

Effect on Completion Deadline
Use Case Diagram pending review

Changes to Completion Criteria
Work done on Use Case Diagram

Start Date: 12 Sep 2023
End Date:

**Comment by lokjunneo** [comment]
Hey, I have some suggested changes after discussing with team.

1. Remove authenticate user
2. Remove <include> between reject work and review work
3. Remove <extend> from view schedule and reject work
4. Change manage accounts to view account, then create, edit, and delete account use cases back to the actor (remove <extend> from them)
5. Add IT admin as new user, with the use cases "create user account" and "delete user account".

**Comment by sn0wyw01f** [comment]
Work Done:

![Image](https://github.com/jacksonhooi/INF2001_P5-4/assets/121973429/aefa6dac-b411-46ac-a53d-dcc837a2f33d)


Effect on Completion Deadline
Use Case Diagram pending review

Changes to Completion Criteria
Made changes to Use Case Diagram

Start Date: 12 Sep 2023
End Date: 13 Sep 2023

**Comment by sn0wyw01f** [comment]
Work Done:

![Image](https://github.com/jacksonhooi/INF2001_P5-4/assets/121973429/e8caf1a0-3c09-4189-bc49-2b551a1cc4cc)

Effect on Completion Deadline
Use Case Diagram pending review

Changes to Completion Criteria
Made changes to Use Case Diagram
- Added change password use case for management and non-management staff

Start Date: 14 Sep 2023
End Date: 15 Sep 2023

**Comment by sn0wyw01f** [comment]
Work Done:
After discussions, we decided to use the 2nd version of the use case diagram.
Attached below is a copy of said diagram it is the same as the one posted on 13 Sep 2023

![Image](https://github.com/jacksonhooi/INF2001_P5-4/assets/121973429/4b513de5-b3e0-45d9-8c22-6f68c41eac4d)

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
All goals completed
Issue can be marked as closed

Start Date: 18 Sep 2023
End Date: 18 Sep 2023

**Comment by Reinakwok** [comment]
Work Done:
Use case diagram finalized

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
All goals completed
Issue can be marked as closed

Start Date: 5 Sept
End Date: 15 Sept
