### ISSUE TITLE
Use Case Description

### ISSUE THREAD

**Issue by jacksonhooi** [jacksonhooi/INF2001_P5-4#14]
Task Description:
Create use case description 

Goals:
1. Review Rejection
2. Assign Work
3. Check Availability
4. Check Work Hours
5. (Admin) View Accounts
6. (Admin) Create Account
7. (Admin) Edit Account
8. (Admin) Delete Account
9. Submit Availability
10. View Schedule
11. Reject Work
--- 

Sheng Long
- [x] 11 Reject Work

Jackson
- [x] 6 (Admin) Create Account
- [x] 8 (Admin) Delete Account

Lok Jun
- [x] 5 (Admin) View Accounts
- [x] 7 (Admin) Edit Account

Reina
- [x] 1 Review Rejection
- [x] 3 Check Availability

Swee Boon
- [x] 2 Assign Work
- [x] 4 Check Work Hours

Yu Jian
- [x] 9 Submit Availability
- [x] 10 View Schedule

Completion Criteria:
Each team member completed allocated task

Allocated Time:

Start Date:12 Sept
End Date:

**Comment by jacksonhooi** [comment]
Work Done:
Allocated task done

Effect on Completion Deadline:
Task has been completed on time


Start Date:12 Sept
End Date:12 Sept

**Comment by jacksonhooi** [comment]
Work Done:
Use Case Description Complete

Effect on Completion Deadline:
Task has been completed on time

All task have been completed by the allocated member 

Issue can be marked as closed

Start Date: 12 Sept
End Date: 18 Sept

**Comment by sweeboon** [comment]
Work Done:
Use case description for 'Assign Work' and 'Check Work Hours' complete

Effect on Completion Deadline: No Effect

Changes to completion criteria: No change

Start Date: 12 Sept
End Date: 18 Sept

**Comment by Reinakwok** [comment]
Done:
Use case description for 'Review Rejection' and 'Check Availability' complete

All task have been completed by the allocated member

Issue can be marked as closed

Start Date: 12 Sept
End Date: 18 Sept

**Comment by yujiannn** [comment]
Work Done:
Use case description for 'Submit Availability' and 'View Schedule' complete

Effect on Completion Deadline: No Effect

Changes to completion criteria: No change

Start Date: 12 Sept
End Date: 18 Sept

**Comment by sn0wyw01f** [comment]
Work Done:
Use case description 11 Reject Work done

Effect on Completion Deadline:
Assigned task completed on time

Changes to Completion Criteria:
All assigned task done

Start Date: 12 Sep
End Date:  18 Sep

**Comment by jacksonhooi** [comment]
Work Done:
All task completed

Effect on Completion Deadline:
Assigned task completed on time

Task has been completed on time
Changes to Completion Criteria
All assigned task completed

Issue can be closed
Start Date: 12 Sept
End Date: 18 Sept
