### ISSUE TITLE
1.6 M1 Project Report

### ISSUE THREAD

**Issue by jacksonhooi** [jacksonhooi/INF2001_P5-4#17]
Task Description:
Writing M1 Project Report 

- [x] 1	Introduction @jacksonhooi 
- [x] 1.1	Product Scope	 @jacksonhooi 
- [x] 1.2	Related Background Literature @yujiannn 	
- [x] 1.3	Intended Audience and Document Overview	@jacksonhooi 
- [x] 1.4	References and Acknowledgments	 @jacksonhooi 
- [x] 2	Overall Description	
- [x] 2.1	Product Overview

	

> Lok Jun

- [x] 2.2	Product Functionality	
Lok Jun
https://github.com/jacksonhooi/INF2001_P5-4/issues/19

- [x] 2.3	Assumptions and Dependencies	
- [x] 3	Specific Requirements	
- [x] 3.1	User Interface Requirements
https://github.com/jacksonhooi/INF2001_P5-4/issues/21	
- [x] 3.2	Functional Requirements	
https://github.com/jacksonhooi/INF2001_P5-4/issues/7
split among all

- [x] 3.3	Use Case Model	
https://github.com/jacksonhooi/INF2001_P5-4/issues/13

- [x] 3.4	Non-functional Requirements	
https://github.com/jacksonhooi/INF2001_P5-4/issues/8

- [x] 3.4.1	Performance Requirements	
- [x] 3.4.2	Safety and Security Requirements	
- [x] 3.5	Other Requirements	
- [x] 4	Project Estimation and Plan	
- [x] 4.1	Software Estimation @yujiannn 
https://github.com/jacksonhooi/INF2001_P5-4/issues/18
- [x] 4.2     Effort Estimation @sweeboon 
- [x] 4.3	Project Management @yujiannn 
- [x] 4.4    Software Development Life Cycle @lokjunneo 

> WBS - Yu Jian
Gantt Chart

- [x] 5	Appendix A – Use Case Descriptions	
https://github.com/jacksonhooi/INF2001_P5-4/issues/14
Split among all

- [x] 6	Appendix B – Data Dictionary	

Completion Criteria:
Complete the report 

Start Date: 5 Sept
End Date: 23 Sept

**Comment by lokjunneo** [comment]
Work Done:
Completed Section 2.1 and 2.2, with a System Architecture Diagram and Activity Diagram.

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria

- [x] 2.1	Product Overview
- [x] 2.2	Product Functionality	

Start Date: 5 Sep 2023
End Date: 20 Sep 2023

**Comment by jacksonhooi** [comment]
Work Done:
Completed Section 1, 1.1, 1.3 and 1.4.

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria

 1 Introduction
 1.1 Product Scope
 1.3 Intended Audience and Document Overview
 1.4 References and Acknowledgments

Start Date: 5 Sep 2023
End Date: 20 Sep 2023

**Comment by yujiannn** [comment]
Work Done:
Completed Task

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria

 1.2 Related Background Literature
 4.1 Software Estimation
 4.3 Project Management 

Start Date: 5 Sep 2023
End Date: 20 Sep 2023

**Comment by Reinakwok** [comment]
Work Done:
Completed Task

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria

- [ ] 3.2 Functional Requirements
- [ ] 3.4 Non-functional Requirements
- [ ] 3.4.1 Performance Requirements
- [ ] 3.4.2 Safety and Security Requirements

Start Date: 5 Sep 2023
End Date: 20 Sep 2023

**Comment by sn0wyw01f** [comment]
Work Done:
Completed Task

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
- [x] 2.3 Assumptions and Dependencies
- [x] 3.3 Use Case Model
- [x] 3.5 Other Requirements
- [x] 6 Appendix B – Data Dictionary

Start Date: 5 Sep 2023
End Date: 20 Sep 2023

**Comment by jacksonhooi** [comment]
Work Done:
Project Report Completed

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
All goals completed

Start Date: 5 Sept 2023
End Date: 23 Sept 2023
