### ISSUE TITLE
#4 Arrange Meeting with Client

### ISSUE THREAD

**Issue by sn0wyw01f** [jacksonhooi/INF2001_P5-4#2]
Task Description:
Arrange meeting with the client so that a date for the face to face/online meeting can be obtained.

Goals:

- [x] Questions to ask client #1  - ALL

- [x] Contact client @Reinakwok 

Completion Criteria:
Successful scheduling of meeting with client
Clarified all questions 

Allocated Time:
1 Week

Start Date: 29 Aug 2023
End Date: 6 Sep 2023

**Comment by lokjunneo** [comment]
Meeting planned at 3.45pm on 4 September 2023 (Monday)

**Comment by sn0wyw01f** [comment]
Work Done:
Meeting has been scheduled with client on Monday, 4 September 2023 on 3.45pm

Effect on Completion Deadline
Client meeting is required to gather requirements for the project
Task has been completed on time

Changes to Completion Criteria
All goals completed
Issue can be marked as closed

Start Date: 3 Sep 2023
End Date: 3 Sep 2023

**Comment by Reinakwok** [comment]
Work Done:
Meeting has been scheduled with client on Monday, 4 September 2023 on 3.45pm

Effect on Completion Deadline:
Client has been contacted for a meeting to gather requirements for the project
Task has been completed on time

Changes to Completion Criteria:
All goals completed
Issue can be marked as closed

Start Date: 3 Sep 2023
End Date: 3 Sep 2023
