### ISSUE TITLE
1.5.2 Effort Estimate

### ISSUE THREAD

**Issue by jacksonhooi** [jacksonhooi/INF2001_P5-4#20]
Task Description:
Effort estimate

Goals:
Effort Estimate

Completion Criteria:
Complete goal

Start Date: 18 Sept
End Date: 22 Sept

**Comment by sweeboon** [comment]
Task Description:
Effort estimate

Goals:
Effort Estimate

Completion Criteria:
Complete goal

Completed On: 20 Sept

**Comment by sweeboon** [comment]
Task Description:
Effort estimate

Goals:
Effort Estimate

Completion Criteria:
Complete goal

Completed On: 20 Sept
