### ISSUE TITLE
1.3.1 Define User Interface Requirements

### ISSUE THREAD

**Issue by Reinakwok** [jacksonhooi/INF2001_P5-4#21]
Task Description:
Discuss with the group and identify non-functional user requirements.

Goals:

 List of user interface requirements created
Completion Criteria

- [x] Successful creation of list of user interface requirements

Allocated Time:
10 Days

Start date: 5 Sept
End date: 15 Sept

**Comment by sweeboon** [comment]
Work Done:
User interface requirement finalized, placed into report

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
All goals completed
Issue can be marked as closed

Task Completed
