### ISSUE TITLE
2.4.3 Class Diagram

### ISSUE THREAD

**Issue by jacksonhooi** [jacksonhooi/INF2001_P5-4#22]
Task Description:
Create class diagram, introduce control class and boundary class

Goals:

- [x] Class Diagram 
- [x] Control Class
- [x] Boundary Class

Completion Criteria:
Need to complete the goal 

Allocated Time
37 Days

Start Date: 25 Sept
End Date: 15 Oct

**Comment by jacksonhooi** [comment]
Work Done:
Class diagram complete

Effect on Completion Deadline
Task has been completed on time


State goals completed 
- [ ] Class Diagram



Start Date: 25 Sept
End Date: 3 Oct

**Comment by sn0wyw01f** [comment]
Work Done:
Control and Boundary classes added to class diagram

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
2 goals completed
- Control Class
- Boundary Class
All goals completed
Issue can be closed, issue completed ahead of schedule

Start Date: 25 Sep 2023
End Date: 3 Oct 2023

**Comment by jacksonhooi** [comment]
Work Done:
All task completed

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria


Issue can be marked as closed

Start Date: 25 Sep 2023
End Date: 3 Oct 2023

**Comment by lokjunneo** [comment]
Hello, some review:
WorkControl need some function to get workload.

Also, might have to check if the functions need parameters or not
