### ISSUE TITLE
M1 Retrospection

### ISSUE THREAD

**Issue by sweeboon** [jacksonhooi/INF2001_P5-4#23]
Task Description:
To complete the team retrospection for M1 milestone
- What went well in milestone one?
- What could be improved? Team dynamics, team management, task allocation and management, etc.
- What will we commit to improve in the next milestone?

Goals:

- [x] M1 Retrospection
- [x] Assign person in charge for point 2 (What could be improved?)
- [x] Assign person in charge for point 3 (What will we commit to improve in the next milestone?)

Completion Criteria:
Successful completion of M1 retrospection and assign persons in charge

Allocated Time:
6 Day

Start Date: 3 Oct 2023
End Date: 9 Oct 2023

**Comment by sweeboon** [comment]
1. Fair distribution of workload, positive team dynamics and objective feedback.
2. More active and organized use of kanban board. 
3. We will give every member a chance to shine while helping each other along.

**Comment by Reinakwok** [comment]
i. Completed tasks, met specific goals, good team dynamics
ii. Better communication, Missed deadlines
iii. We will work on enhancing communication channels within the team, and improve our task allocation process. We will refine our project management strategies, including setting clearer goals, defining project milestones, and regularly reviewing progress to stay on track.

**Comment by lokjunneo** [comment]
1. We did well for everything. I believe we did well for the report.
2. Could be better with task allocation and resource management.
3. Maybe we can have a consistent meeting routine where we review each others tasks and work.

**Comment by sn0wyw01f** [comment]
i. Positive working environment, even task distribution
ii. More frequent update of Kanban board
iii. Better documentation to keep issues up to date

**Comment by jacksonhooi** [comment]
i.  Able to finish all the task, team able to complete allocate task properly
 ii. Can improve on task allocation and update kanban board regularly
 iii.  We will improve on communication and update each other on task progress

**Comment by yujiannn** [comment]
1. Collaborated well as a team, able to finish tasks successfully with good quality
2. Could have delegated tasks more evenly, could have sought more feedbacks from professor in every steps
3. Reach out to professor more proactively and regularly, asking for their feedback and advice

**Comment by jacksonhooi** [comment]
Work Done:
Assign person in charge for point 2 and point 3

- [ ] Assign person in charge for point 2 (What could be improved?) @sweeboon 
- [ ] Assign person in charge for point 3 (What will we commit to improve in the next milestone?) @jacksonhooi 



Start Date: 3 Oct 2023
End Date: 16 Oct 2023

**Comment by sweeboon** [comment]
Task Description:
To complete the team retrospection for M1 milestone

Completed On: 17 Oct 2023
