### ISSUE TITLE
2.4.1 Component Diagram

### ISSUE THREAD

**Issue by sn0wyw01f** [jacksonhooi/INF2001_P5-4#25]
Task Description:
Create component diagram for the project as stated in M2 submission

Goals:
- [x] Create Component Diagram

Completion Criteria:
Successful creation of the component diagram

Allocated Time:
7 Days

Start Date: 16 Oct 2023
End Date: 23 Oct 2023

**Comment by sweeboon** [comment]
Work Done:
All task completed

Effect on Completion Deadline
Slight delays due to unforeseen need for ongoing collaboration with class diagram developers

Changes to Completion Criteria
All goals completed

Issue can be marked as closed

Start Date: 25 Sep 2023
End Date: 27 Oct 2023

**Comment by Reinakwok** [comment]
Work Done:
All task completed

Effect on Completion Deadline
Slight delays due to unforeseen need for ongoing collaboration with class diagram developers

Changes to Completion Criteria
All goals completed

Issue can be marked as closed

Start Date: 25 Sep 2023
End Date: 27 Oct 2023
