### ISSUE TITLE
2.4.4 M2 Project Report

### ISSUE THREAD

**Issue by jacksonhooi** [jacksonhooi/INF2001_P5-4#27]
Task Description:
Write M2 Project Report

Goals

- [x] 1 Introduction
- [x] 1.1 Product Scope Changes
- [x] 1.2 References and Acknowledgements

- [x] 2 Changes in Requirements

- [x] 3 Software Design
- [x] 3.1 Component Diagram #25 
- [x] 3.2 Sequence Diagram #24 

- [x] 4 Updated Project Plan
- [x] 5 Appendix A - Updated Use Case Descriptions
- [x] 6 Appendix C - Overall Class Diagram
- [x] 7 Appendix C - Data Dictionary

Completion Criteria:
All M2 project report sections to be completed

Allocated Time:
12 Days

Start Date: 16 Oct 2023
End Date: 28 Oct 2023

**Comment by lokjunneo** [comment]
Work Done:
Updated Use Case Description for UC2

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
Completed sub task "Use Case 2"

Start Date: 17 Oct
End Date: 18 Oct

**Comment by lokjunneo** [comment]
Work Done:
Sequence Diagram

Effect on Completion Deadline
Task completed on time

Changes to Completion Criteria
Task completed successfully

Start Date: 16/10/2023
End Date: 23/10/2023

**Comment by jacksonhooi** [comment]
Work Done:
Introduction, Product Scope Changes and Overall Class Diagram

Effect on Completion Deadline
Task completed on time

Changes to Completion Criteria
Task completed successfully

Start Date: 16/10/2023
End Date: 28/10/2023
