### ISSUE TITLE
2.3.2 Updated Use Case Descriptions

### ISSUE THREAD

**Issue by jacksonhooi** [jacksonhooi/INF2001_P5-4#28]
Task Description:
Review use case description in M1

Goals:
Complete review the use case description

Completion Criteria:

- [x]  Assign Work @lokjunneo 
- [x] (Admin) Create Account @jacksonhooi 
- [x] (Admin) Edit Account  @jacksonhooi 
- [x] (Admin) Delete Account @jacksonhooi 
- [x] Submit Availability @yujiannn 

Start Date: 18 Oct 2023
End Date:  28 Oct 2023

**Comment by lokjunneo** [comment]
Work Done:
Assign Work 

Effect on Completion Deadline
Task has been completed successfully

Changes to Completion Criteria
No changes

Start Date: 20/10/2023
End Date: 20/10/2023

**Comment by jacksonhooi** [comment]
Work Done:
Assign Work

Effect on Completion Deadline
Task has been completed successfully

Changes to Completion Criteria
No changes

Start Date: 23/10/2023
End Date: 23/10/2023

**Comment by yujiannn** [comment]
Work Done:
Assign Work

Effect on Completion Deadline
Task has been completed successfully

Changes to Completion Criteria
No changes

Start Date: 23/10/2023
End Date: 23/10/2023
