### ISSUE TITLE
#6 Process Meeting Minutes from Client Meeting

### ISSUE THREAD

**Issue by jacksonhooi** [jacksonhooi/INF2001_P5-4#3]
Task Description:
During the client meeting, meeting minute/notes should be taken down, this is to keep track of
- what was discussed
- what questions were answered
- any special requests/conditions for the client
- information about the client company/stakeholders

After the meeting
Analyze the notes taken and come up with functional and non-functional requirements.
Evaluate feasibility of requirements, check for conflicts.
Based on requirements can start planning for the approach to take for the project.
Create Software Requirements Specification (SRS)

Goals:

- [x] Record meeting minutes/notes @sn0wyw01f 
- [x] #7  
- [x] #8  

Completion Criteria:
Successful creation of list of functional and non-functional requirements for the project

Allocated Time:

Start Date: 4 Sep 2023
End Date:

**Comment by sweeboon** [comment]
Link to the meeting minutes: https://docs.google.com/document/d/1YSKkZHnETn72bH9ce0dqCbuDwaFcMvz1ssypubHcaKg/edit?usp=sharing

**Comment by jacksonhooi** [comment]
Work Done:
All the goals are met

Effect on Completion Deadline:
Task has been completed on time

Issue can be marked as closed

Start Date: 4 Sept 2023
End Date: 13 Sept 2023

**Comment by Reinakwok** [comment]
Work Done:
All the goals are met

Effect on Completion Deadline:
Task has been completed on time

Issue can be marked as closed

Start Date: 4 Sept 2023
End Date: 13 Sept 2023
