### ISSUE TITLE
1.3.3 Intended Audience and Document Overview

### ISSUE THREAD

**Issue by yujiannn** [jacksonhooi/INF2001_P5-4#32]
Task Description:
Fill in the section in report

Goals:
Complete the task

Completion Criteria:

Allocated Time: 1 Day

Start Date: Sep 11 
End Date: Sep 12

**Comment by jacksonhooi** [comment]
Work Done:
All task completed

Effect on Completion Deadline:
Assigned task completed on time

Task has been completed on time
Changes to Completion Criteria
All assigned task completed

Issue can be closed
Start Date: 11 Sept
End Date: 12 Sept
