### ISSUE TITLE
1.4.3 Assumptions and Dependencies

### ISSUE THREAD

**Issue by yujiannn** [jacksonhooi/INF2001_P5-4#36]
Task Description:
Describe the logical characteristics of each interface between the software product and the users

Goals:
Complete the task

Completion Criteria:
All assumptions and dependencies for M1 stated

Allocated Time: 3 Days

Start Date: Sep 15
End Date: Sep 18

**Comment by sn0wyw01f** [comment]
Work Done:
All assumptions and dependencies for the project written for M1 report.
Total of 2 assumptions are in the M1 report.

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
All goals completed
Issue can be marked as closed

Start Date: 16 Sep 2023
End Date: 17 Sep 2023
