### ISSUE TITLE
2.2.1 Product Scope Changes

### ISSUE THREAD

**Issue by Reinakwok** [jacksonhooi/INF2001_P5-4#49]
Task Description:
Fill up the product scope changes in the report

Completion Criteria:
Complete the task

Allocated Time:
10 days

Start Date:18 Oct 2023
End Date: 28 Oct 2023

**Comment by jacksonhooi** [comment]
Work Done:
Completed filling up the report

Changes to Completion Criteria
Task completed

Issue can be marked as closed

Start Date: 28 Oct 2023
End Date: 28 Oct 2023
