### ISSUE TITLE
2.2.2 References and Acknowledgements

### ISSUE THREAD

**Issue by Reinakwok** [jacksonhooi/INF2001_P5-4#50]

**Comment by sn0wyw01f** [comment]
Work Done:
Completed Task, no references and acknowledgements in M2 report as no external sources are used

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
All tasks done, issue can be closed

Start Date: 18 Sep 2023
End Date: 28 Sep 2023
