### ISSUE TITLE
2.4.3.1  Class Diagram: Entity and Control Classes

### ISSUE THREAD

**Issue by Reinakwok** [jacksonhooi/INF2001_P5-4#53]
Task Description:
Create entity class and control class

Completion Criteria:
complete the task

Allocated Time:
14 days

Start Date: 25 Sep 2023
End Date: 09 Oct 2023

**Comment by jacksonhooi** [comment]
Work Done:
Finish creating entity class and control class

Effect on Completion Deadline
Task has been delayed due to changes to the classes


Issue can be marked as closed

Start Date: 25 Sep 2023
End Date: 28 Oct 2023
