### ISSUE TITLE
2.4.3.2 Class Diagram: Boundary and Interface Classes

### ISSUE THREAD

**Issue by Reinakwok** [jacksonhooi/INF2001_P5-4#54]
ask Description:
Create Boundary and Interface Classes

Completion Criteria:
complete the task

Allocated Time:
14 days

Start Date: 09 Oct 2023
End Date: 23 Oct 2023

**Comment by sn0wyw01f** [comment]
Work Done:
Control and Boundary classes added to class diagram

Effect on Completion Deadline
Task has been completed

Changes to Completion Criteria
All goals completed
Issue can be closed

Start Date: 25 Sep 2023
End Date: 3 Oct 2023
