### ISSUE TITLE
#8 Identify Functional User Requirements

### ISSUE THREAD

**Issue by jacksonhooi** [jacksonhooi/INF2001_P5-4#7]
Task Description:
Discuss with group and identify functional user requirements.

Initial Requirements (from project brief)
1. The app should be Web-based in a language of your choosing
2. The manager should be able to visualise the staff workload immediately on the landing page
3. The manager should be able to allocate jobs to staff for one week at a time
4. The manager should be able to view up to three staff availability and any relevant information
to make the job assignment easier on the job allocation page
5. When displaying the staff availability, the workload assigned, staff’s job preference, staff’s
location at a particular date, and availabilities for the week should be shown
6. On the manager’s landing page, the top three staff with the lowest workload should be shown,
and highlight all staff over 40 hours of jobs allocated
7. Staff should be able to view their weekly job assignments and overall workload for the month
on their landing page
8. Staff can add and edit their availabilities up to 5 weeks ahead of time.
9. Staff can indicate their job preference for the week
10. Staff can reject jobs assigned to them, but they will be warned to discuss the jobs with their
manager before proceeding with the rejection
11. The company’s IT administrators will oversee adding new staff and managers to the system

Goals:

- [x] List of functional requirements created

Completion Criteria: Identified Functional User Requirements has been compiled and confirmed. 
Successful creation of list of functional requriements

Allocated Time:
10 Days

Start date: 5 Sept
End date: 15 Sept

**Comment by Reinakwok** [comment]
The manager should be able to allocate jobs to staff for one week at a time

**Comment by Reinakwok** [comment]
The manager should be able to allocate jobs to staff for one week at a time

**Comment by Reinakwok** [comment]
The manager should be able to view up to three staff availability and any relevant information

**Comment by jacksonhooi** [comment]
When displaying the staff availability, the workload assigned, staff’s job preference, staff’s location at a particular date, and availabilities for the week should be shown

**Comment by lokjunneo** [comment]
On the manager’s landing page, the top three staff with the lowest workload should be shown.

**Comment by yujiannn** [comment]
Staff should be able to view their weekly job assignments.
Staff  should be able to view their overall workload for the month on their landing page.

**Comment by lokjunneo** [comment]
On the staff landing page, staff should be able to view their weekly job assignments.
On the staff landing page, staff should be able to view their overall workload for the month.

**Comment by sn0wyw01f** [comment]
Staff should be able to reject jobs assigned to them
The company’s IT administrators should be able to add new staff and managers to the system

**Comment by lokjunneo** [comment]
> The manager should be able to view up to three staff availability and any relevant information
to make the job assignment easier on the job allocation page

Need to define "three staff availability" and what "relevant information" is.

**Comment by lokjunneo** [comment]
> Staff can indicate their job preference for the week

Do they indicate it together with availability?
When is this job preference shown to the managers?

**Comment by jacksonhooi** [comment]
Work Done:
Functional user requirement finalized

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
All goals completed
Issue can be marked as closed

Start Date: 5 Sept
End Date: 15 Sept

**Comment by Reinakwok** [comment]
Work Done:
Functional user requirement finalized, placed into report

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
All goals completed
Issue can be marked as closed

Start Date: 5 Sept
End Date: 15 Sept
