### ISSUE TITLE
#9 Identify Non-Functional User Requirements

### ISSUE THREAD

**Issue by Reinakwok** [jacksonhooi/INF2001_P5-4#8]
Task Description:
Discuss with the group and identify non-functional user requirements.

Initial Requirements (from project brief)
1. The app should be Web-based in a language of your choosing
2. The manager should be able to visualise the staff workload immediately on the landing page
3. The manager should be able to allocate jobs to staff for one week at a time
4. The manager should be able to view up to three staff availability and any relevant information
to make the job assignment easier on the job allocation page
5. When displaying the staff availability, the workload assigned, staff’s job preference, staff’s
location at a particular date, and availabilities for the week should be shown
6. On the manager’s landing page, the top three staff with the lowest workload should be shown,
and highlight all staff over 40 hours of jobs allocated
7. Staff should be able to view their weekly job assignments and overall workload for the month
on their landing page
8. Staff can add and edit their availabilities up to 5 weeks ahead of time.
9. Staff can indicate their job preference for the week
10. Staff can reject jobs assigned to them, but they will be warned to discuss the jobs with their
manager before proceeding with the rejection
11. The company’s IT administrators will oversee adding new staff and managers to the system

Goals:

- [x] List of non-functional requirements created

Completion Criteria
Successful creation of list of non functional requirements

Allocated Time:
10 Days

Start date: 5 Sept
End date: 15 Sept

**Comment by Reinakwok** [comment]
The app should be Web-based in a language of your choosing

**Comment by Reinakwok** [comment]
The manager should be able to visualise the staff workload immediately on the landing page.
What does immediately mean? eg 1 sec? etc

**Comment by yujiannn** [comment]
How many concurrent users should the system be able to handle without experiencing any performance issues?
 How critical is it for the system to be available and accessible at all times? Are there any specific uptime requirements?

**Comment by Reinakwok** [comment]
The system is able to handle few tenths of staffs (10) without experiencing any performance issues

**Comment by Reinakwok** [comment]
Work Done:
Non Functional user requirement finalized

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
All goals completed
Issue can be marked as closed

Start Date: 5 Sept
End Date: 15 Sept

**Comment by sweeboon** [comment]
Work Done:
Non Functional user requirement finalized

Effect on Completion Deadline
Task has been completed on time

Changes to Completion Criteria
All goals completed
Issue can be marked as closed

Start Date: 5 Sept
End Date: 15 Sept
